name: Test & Lint

on: [push, pull_request]

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W rust-2021-compatibility"
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-24.04
    env:
      CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

      # This plugin should be loaded after toolchain setup
      - name: Cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@419f0f955ea0cf384c06ae25b10b8d3bcba087da # cargo-llvm-cov

      - name: Test and generate coverage
        run: >-
          cargo llvm-cov --all-features --workspace --lcov
          --remap-path-prefix --output-path lcov.info

      - name: Upload coverage to Codacy
        if: env.CODACY_API_TOKEN != ''
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          api-token: ${{ env.CODACY_API_TOKEN }}
          coverage-reports: lcov.info
          language: Rust
          force-coverage-parser: lcov

  lints:
    name: Lints
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          components: rustfmt, clippy

      # This plugin should be loaded after toolchain setup
      - name: Cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check --color always

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
