# @orcastrate
# template: pr-title
# @end-orcastrate

name: Check PR title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-26.04
    permissions:
      pull-requests: read
      statuses: write
    steps:
      - name: Check Conventional Commit title
        uses: aslafy-z/conventional-pr-title-action@a0b851005a0f82ac983a56ead5a8111c0d8e044a # v3.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
