name: Publish

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag to publish'
        required: true
        type: string

jobs:
  publish-cratesio:
    name: Publish to crates.io
    runs-on: ubuntu-24.04
    environment: "publish-crates.io"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.tag-name }}

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      # This plugin should be loaded after toolchain setup
      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Upload to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-homebrew:
    name: Publish to Homebrew
    runs-on: ubuntu-24.04
    environment: "publish-homebrew"
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: vscli
          homebrew-tap: michidk/homebrew-tools
          tag-name: ${{ github.event.inputs.tag-name }}
          commit-message: |
            Update {{formulaName}} to version {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
