name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  APP_NAME: vscli

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-24.04
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get release version
        if: env.VERSION == ''
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "Version: ${{ env.VERSION }}"

      - name: Create release
        id: release
        uses: mikepenz/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ env.VERSION }}
          draft: true
          generate_release_notes: true

  build-release:
    name: Build release
    needs: ['create-release']
    runs-on: ${{ matrix.os }}
    env:
      CARGO: cargo
      TARGET_FLAGS: ""
      TARGET_DIR: ./target
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl
        - build: linux-arm
          os: ubuntu-latest
          target: arm-unknown-linux-gnueabihf
        - build: macos
          os: macos-latest
          target: x86_64-apple-darwin
        - build: macos-arm
          os: macos-latest
          target: aarch64-apple-darwin
        - build: win32-msvc
          os: windows-latest
          target: i686-pc-windows-msvc
        - build: win-msvc
          os: windows-latest
          target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup target
        if: matrix.target != ''
        run: |
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
          echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

      - name: Setup Cross
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cross
          echo "CARGO=cross" >> $GITHUB_ENV

      - name: Show command used for Cargo
        run: |
          echo "cargo command is: ${{ env.CARGO }}"
          echo "target flag is: ${{ env.TARGET_FLAGS }}"
          echo "target dir is: ${{ env.TARGET_DIR }}"

      - name: Build release binary
        run: ${{ env.CARGO }} build --release --verbose ${{ env.TARGET_FLAGS }}

      - name: Strip release binary (linux)
        if: matrix.build == 'linux' || matrix.os == 'macos'
        run: strip "${{ env.TARGET_DIR }}/release/${{ env.APP_NAME }}"

      - name: Strip release binary (arm)
        if: matrix.build == 'linux-arm'
        run: |
          docker run --rm -v \
            "$PWD/target:/target:Z" \
            rustembedded/cross:arm-unknown-linux-gnueabihf \
            arm-linux-gnueabihf-strip \
            /target/arm-unknown-linux-gnueabihf/release/${{ env.APP_NAME }}

      - name: Build archive
        run: |
          staging="${{ env.APP_NAME }}-${{ matrix.target }}"
          mkdir -p "$staging"
          if [[ "${{ matrix.os }}" = "windows-latest" ]]; then
            cp "${{ env.TARGET_DIR }}/release/${{ env.APP_NAME }}.exe" "$staging/"
            7z a "$staging.zip" "$staging"
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            cp "${{ env.TARGET_DIR }}/release/${{ env.APP_NAME }}" "$staging/"
            tar czf "$staging.tar.gz" "$staging"
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload archive
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/octet-stream

  publish-release:
    name: Publish release
    needs: ['build-release']
    runs-on: ubuntu-24.04
    steps:
      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit "${{ github.ref_name }}" --repo "${{ github.repository }}" --draft=false
